#!/usr/bin/env python3
"""
Use psycopg2 to directly connect to Supabase PostgreSQL database
This bypasses the PostgREST API layer entirely
"""
from dotenv import load_dotenv
import os

load_dotenv()

# Supabase provides a direct PostgreSQL connection string
# Format: postgresql://postgres:[PASSWORD]@db.[PROJECT_REF].supabase.co:5432/postgres

supabase_url = os.getenv("SUPABASE_URL")  # https://cckztschedgwwutrasev.supabase.co
project_ref = supabase_url.split("//")[1].split(".")[0] if supabase_url else None

print(f"Project Ref: {project_ref}")
print()
print("⚠️  需要 DATABASE PASSWORD（不是 API Key）")
print("請到 Supabase Dashboard -> Settings -> Database -> Connection String")
print("找到 'Password' 欄位的密碼")
print()

# Check if we have psycopg2
try:
    import psycopg2
    print("✅ psycopg2 installed")
except ImportError:
    print("❌ psycopg2 not installed")
    print("   Installing psycopg2-binary...")
    import subprocess
    subprocess.check_call(["pip", "install", "psycopg2-binary"])
    import psycopg2
    print("✅ psycopg2-binary installed successfully")

# Prompt for password (or read from env)
db_password = os.getenv("SUPABASE_DB_PASSWORD")
if not db_password:
    print("\n請在 .env 檔案中加入:")
    print("SUPABASE_DB_PASSWORD=你的資料庫密碼")
    print("\n或者我們可以用 REST API 的方式重新嘗試...")
    exit(1)

# Build connection string
conn_string = f"postgresql://postgres.{project_ref}:{db_password}@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"

print(f"\n嘗試連線到: postgresql://postgres.{project_ref}:***@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres")

try:
    conn = psycopg2.connect(conn_string)
    print("✅ PostgreSQL 連線成功！")
    
    cursor = conn.cursor()
    
    # Check if table exists
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'predictions'
        );
    """)
    table_exists = cursor.fetchone()[0]
    
    if table_exists:
        print("✅ 'predictions' 表格存在")
        
        # Count rows
        cursor.execute("SELECT COUNT(*) FROM predictions;")
        count = cursor.fetchone()[0]
        print(f"   目前有 {count} 筆資料")
    else:
        print("❌ 'predictions' 表格不存在！")
        print("   正在建立...")
        
        cursor.execute("""
            CREATE TABLE predictions (
                id bigint generated by default as identity primary key,
                created_at timestamp with time zone default timezone('utc'::text, now()) not null,
                index_name text,
                model_name text,
                ticker text,
                current_price numeric,
                predicted_price numeric,
                potential numeric,
                period text,
                timestamp timestamp with time zone
            );
        """)
        conn.commit()
        print("✅ 表格建立成功")
    
    cursor.close()
    conn.close()
    
except Exception as e:
    print(f"❌ 連線失敗: {e}")
    print("\n請確認:")
    print("1. SUPABASE_DB_PASSWORD 是否正確")
    print("2. 資料庫是否允許外部連線")
