"""
Database management for stock prediction application.
Currently supports MySQL and MongoDB. Will be migrated to Supabase in Phase 2.
"""
import datetime
import os
from contextlib import contextmanager
try:
    import mysql.connector
    from mysql.connector import Error, pooling
    HAS_MYSQL = True
except ImportError:
    HAS_MYSQL = False

try:
    from pymongo import MongoClient
    HAS_MONGO = True
except ImportError:
    HAS_MONGO = False

try:
    from supabase import create_client, Client
    HAS_SUPABASE = True
except ImportError:
    HAS_SUPABASE = False

from typing import List, Tuple, Optional, Any
from config import DatabaseConfig, config
from logger import logger



class SupabaseManager:
    """Manager for Supabase connection and operations"""
    
    def __init__(self):
        self.enabled = False
        url = config.supabase_url
        
        # Prioritize service_role key (full admin access) over publishable key
        key = os.getenv("SUPABASE_SERVICE_KEY") or config.supabase_key
        
        if not HAS_SUPABASE:
            logger.warning("⚠ 警告: 未安裝 supabase 套件")
            return
            
        if not url or not key:
            logger.warning("⚠ 警告: Supabase URL 或 Key 未設定")
            return
            
        try:
            self.client: Client = create_client(url, key)
            self.enabled = True
            logger.info("Supabase 連接初始化成功")
        except Exception as e:
            logger.error(f"Supabase 連線失敗: {str(e)}")
            self.enabled = False

    def save_predictions(self, index_name: str, predictions: List[Tuple], model_name: str, period: str):
        """
        Save prediction results to Supabase 'predictions' table
        
        Args:
            index_name: Name of stock index (e.g., '台灣50')
            predictions: List of tuples (ticker, potential, current, predicted)
            model_name: Name of the model (e.g., 'LSTM')
            period: Training period (e.g., '6mo')
        """
        if not self.enabled:
            return

        data = []
        timestamp = datetime.datetime.now().isoformat()
        
        for p in predictions:
            # p format: (ticker, potential, current_price, predicted_price)
            # Handle pandas types if necessary
            import pandas as pd
            tk = p[0]
            pot = float(p[1].iloc[0]) if isinstance(p[1], pd.Series) else float(p[1])
            cur = float(p[2].iloc[0]) if isinstance(p[2], pd.Series) else float(p[2])
            pred = float(p[3].iloc[0]) if isinstance(p[3], pd.Series) else float(p[3])

            record = {
                "index_name": index_name,
                "model_name": model_name,
                "ticker": tk,
                "potential": pot,
                "current_price": cur,
                "predicted_price": pred,
                "period": period,
                "timestamp": timestamp
            }
            data.append(record)
            
        try:
            # Perform batch insert
            self.client.table("predictions").insert(data).execute()
            logger.info(f"✅ 成功寫入 {len(data)} 筆預測結果到 Supabase (Model: {model_name})")
        except Exception as e:
            logger.error(f"❌ Supabase 寫入失敗: {str(e)}")
            if "relation" in str(e) and "does not exist" in str(e):
                 logger.warning("💡 提示: 請確認您的 Supabase 資料庫中已建立 'predictions' 資料表。")
                 print("   您可以在 SQL Editor 執行以下指令：") # Keep SQL instructions as print for copy-paste visibility? Or logger.warning? Logger is better but standard format adds timestamp. Print is cleaner for block copy. I will keep print for SQL block.
                 print("   CREATE TABLE predictions (")
                 print("       id bigint generated by default as identity primary key,")
                 print("       created_at timestamp with time zone default timezone('utc'::text, now()) not null,")
                 print("       index_name text, model_name text, ticker text,")
                 print("       current_price numeric, predicted_price numeric, potential numeric,")
                 print("       period text, timestamp timestamp with time zone")
                 print("   );")


class MySQLManager:
    """
    MySQL database manager for stock predictions.
    Note: This will be replaced with Supabase in Phase 2.
    """
    
    def __init__(self):
        self.enabled = DatabaseConfig.USE_MYSQL and HAS_MYSQL
        self.connection = None
        if not HAS_MYSQL and DatabaseConfig.USE_MYSQL:
            print("⚠ 警告: 未安裝 MySQL 連接器，MySQL 功能已停用")
            
        if not self.enabled:
            # print("MySQL 功能未啟用")
            return
            
        try:
            print("嘗試連接 MySQL...")
            print(f"Host: {DatabaseConfig.MYSQL_HOST}")
            print(f"Database: {DatabaseConfig.MYSQL_DATABASE}")
            
            self.connection = mysql.connector.connect(
                host=DatabaseConfig.MYSQL_HOST,
                user=DatabaseConfig.MYSQL_USER,
                password=DatabaseConfig.MYSQL_PASSWORD,
                database=DatabaseConfig.MYSQL_DATABASE,
                port=DatabaseConfig.MYSQL_PORT
            )
            print("MySQL 連接成功")
            self.create_prediction_table()
            
        except Error as e:
            print(f"MySQL 連接錯誤: {e}")
            self.connection = None
            self.enabled = False
    
    def create_prediction_table(self):
        """Create stock_predictions table if it doesn't exist"""
        if not self.enabled or not self.connection:
            return
        
        try:
            cursor = self.connection.cursor()
            
            # Check if table exists
            check_table_query = """
            SELECT COUNT(*)
            FROM information_schema.tables
            WHERE table_schema = %s
            AND table_name = 'stock_predictions'
            """
            cursor.execute(check_table_query, (DatabaseConfig.MYSQL_DATABASE,))
            table_exists = cursor.fetchone()[0] > 0
            
            if table_exists:
                print("stock_predictions 表已存在，跳過創建")
            else:
                # Create table
                create_table_query = """
                CREATE TABLE IF NOT EXISTS stock_predictions (
                    id INT AUTO_INCREMENT PRIMARY KEY,
                    calculation_date DATE,
                    calculation_time TIME,
                    index_name VARCHAR(50),
                    stock_symbol VARCHAR(20),
                    current_price DECIMAL(10,2),
                    predicted_price DECIMAL(10,2),
                    potential DECIMAL(10,4),
                    prediction_method VARCHAR(20),
                    period_param VARCHAR(10),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )
                """
                cursor.execute(create_table_query)
                self.connection.commit()
                print("成功創建 stock_predictions 表")
        
        except Error as e:
            print(f"檢查/創建表格時發生錯誤: {e}")
        finally:
            cursor.close()
    
    def save_predictions(
        self, 
        index_name: str, 
        predictions: List[Tuple[str, float, float, float]], 
        method: str, 
        period: str
    ):
        """
        Save predictions to MySQL database
        
        Args:
            index_name: Name of the stock index (e.g., "SP500")
            predictions: List of tuples (ticker, potential, current_price, predicted_price)
            method: Prediction method name (e.g., "LSTM", "Prophet")
            period: Time period used for prediction
        """
        if not self.enabled or not self.connection:
            return
        
        try:
            cursor = self.connection.cursor()
            current_date = datetime.datetime.now().date()
            current_time = datetime.datetime.now().time()
            
            insert_query = """
            INSERT INTO stock_predictions 
            (calculation_date, calculation_time, index_name, stock_symbol, 
             current_price, predicted_price, potential, prediction_method, period_param)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
            """
            
            for ticker, potential, current_price, predicted_price in predictions:
                # Handle pandas Series conversion
                import pandas as pd
                data = (
                    current_date,
                    current_time,
                    index_name,
                    ticker,
                    float(current_price.iloc[0]) if isinstance(current_price, pd.Series) else float(current_price),
                    float(predicted_price.iloc[0]) if isinstance(predicted_price, pd.Series) else float(predicted_price),
                    float(potential.iloc[0]) if isinstance(potential, pd.Series) else float(potential),
                    method,
                    period
                )
                cursor.execute(insert_query, data)
            
            self.connection.commit()
            print(f"成功保存 {len(predictions)} 條 {method} 預測結果到 MySQL")
        
        except Error as e:
            print(f"保存到 MySQL 時發生錯誤: {e}")
        finally:
            cursor.close()
    
    def close(self):
        """Close MySQL connection"""
        if self.connection and self.connection.is_connected():
            self.connection.close()
            print("MySQL 連接已關閉")
    
    def __enter__(self):
        """Context manager entry"""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        self.close()


def save_to_mongodb(index_name: str, stock_predictions: dict):
    """
    Save stock predictions to MongoDB
    Note: This will be replaced with Supabase in Phase 2.
    
    Args:
        index_name: Name of the stock index
        stock_predictions: Dictionary of prediction results
    """
    if not HAS_MONGO:
        print("MongoDB 功能未啟用或未安裝 pymongo")
        return

    client = None
    try:
        client = MongoClient(DatabaseConfig.MONGO_URI)
        db = client[DatabaseConfig.MONGO_DB_NAME]
        collection = db["predictions"]
        
        # Prepare document for insertion
        record = {
            "index": index_name,
            "timestamp": datetime.datetime.now(),
            "predictions": stock_predictions
        }
        
        # Insert into MongoDB
        collection.insert_one(record)
        print(f"成功將 {index_name} 結果寫入 MongoDB")
        
    except Exception as e:
        print(f"⚠️ 寫入 MongoDB 失敗: {str(e)}")
    finally:
        if client:
            client.close()
