-- Run this in Supabase SQL Editor
CREATE TABLE predictions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    index_name text,
    model_name text,
    ticker text,
    current_price numeric,
    predicted_price numeric,
    potential numeric,
    period text,
    timestamp timestamp with time zone
);

ALTER TABLE predictions ENABLE ROW LEVEL SECURITY;

-- Allow anonymous access for prototype/testing (using Publishable Key)
CREATE POLICY "Allow public select" ON predictions FOR SELECT USING (true);
CREATE POLICY "Allow public insert" ON predictions FOR INSERT WITH CHECK (true);
