-- Enhanced Supabase Schema for Backtesting
-- Adds actual_price tracking and performance metrics

-- Main predictions table (existing)
CREATE TABLE IF NOT EXISTS predictions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    index_name text,
    model_name text,
    ticker text,
    current_price numeric,
    predicted_price numeric,
    potential numeric,
    period text,
    timestamp timestamp with time zone,
    
    -- NEW: Backtesting fields
    actual_price numeric,  -- Actual price after prediction period
    actual_date timestamp with time zone,  -- Date when actual price was recorded
    accuracy numeric,  -- (actual_price - current_price) / (predicted_price - current_price)
    absolute_error numeric,  -- ABS(predicted_price - actual_price)
    percentage_error numeric  -- (predicted_price - actual_price) / actual_price * 100
);

-- Index for faster backtesting queries
CREATE INDEX IF NOT EXISTS idx_predictions_ticker_timestamp ON predictions(ticker, timestamp);
CREATE INDEX IF NOT EXISTS idx_predictions_model_timestamp ON predictions(model_name, timestamp);
CREATE INDEX IF NOT EXISTS idx_predictions_backtest ON predictions(ticker, timestamp) WHERE actual_price IS NOT NULL;

-- View for model performance analysis
CREATE OR REPLACE VIEW model_performance AS
SELECT 
    model_name,
    index_name,
    COUNT(*) as total_predictions,
    COUNT(actual_price) as verified_predictions,
    AVG(accuracy) as avg_accuracy,
    AVG(ABS(percentage_error)) as avg_abs_error,
    STDDEV(percentage_error) as error_std_dev,
    COUNT(CASE WHEN (predicted_price > current_price AND actual_price > current_price) 
               OR (predicted_price < current_price AND actual_price < current_price) 
          THEN 1 END) * 100.0 / NULLIF(COUNT(actual_price), 0) as direction_accuracy
FROM predictions
WHERE actual_price IS NOT NULL
GROUP BY model_name, index_name;

-- View for recent predictions needing verification
CREATE OR REPLACE VIEW predictions_to_verify AS
SELECT 
    id,
    ticker,
    model_name,
    timestamp,
    current_price,
    predicted_price,
    potential,
    period,
    -- Calculate target date based on period
    CASE 
        WHEN period = '1mo' THEN timestamp + interval '1 month'
        WHEN period = '3mo' THEN timestamp + interval '3 months'
        WHEN period = '6mo' THEN timestamp + interval '6 months'
        WHEN period = '1y' THEN timestamp + interval '1 year'
        ELSE timestamp + interval '1 month'
    END as target_date
FROM predictions
WHERE actual_price IS NULL
  AND timestamp < NOW() - interval '1 day'  -- At least 1 day old
ORDER BY timestamp DESC;

COMMENT ON TABLE predictions IS 'Stock price predictions with backtesting support';
COMMENT ON COLUMN predictions.actual_price IS 'Actual stock price observed after prediction period';
COMMENT ON COLUMN predictions.accuracy IS 'Prediction accuracy: 1.0 = perfect, 0.0 = no better than baseline';
